### PR TITLE
fix typo in galaxy param

### PR DESCRIPTION
**Pull request by andylash**
Alas, i had this param slightly wrong as per Galaxy support.

### CODE REVIEW

**Comment by maxkferg** [comment]
@andylash I appreciate this fix

**Comment by andylash** [comment]
could you publish 1.2.6?

thanks,
andy

**Comment by maxkferg** [comment]
Alright, we just published 1.2.8 which includes this pull request and working test cases

**Comment by andylash** [comment]
thanks!

**Comment by kulttuuri** [comment]
Sorry for hijacking this thread, but didn't find any other place to comment this. Could you @maxkferg open the issues section of this extension so there is an way to send feedback / issues related to the extension? :)

**Comment by maxkferg** [comment]
@kulttuuri. Alright issues is open

**Comment by kulttuuri** [comment]
👍  :)

**Pull request merged**
